// Japanese UI copy dictionary (SPEC-050 section 24.3 / 27). Leaves are strings or templates.

export const copy = {
  pageTitle: {
    announcements: "お知らせ",
    announcementDetail: "お知らせ詳細",
    karaoke: "Karaoke販売案内",
    karaokeDay: "Karaoke空き状況",
    goods: "Goods",
  },
  pageState: {
    loading: "読み込み中です",
    empty: "現在公開中の情報はありません",
    unavailable: (subject: string): string => `${subject}を取得できません`,
    retry: "再読み込み",
  },
  home: {
    fallbackHeading: "Event Home",
    subject: "Event情報",
    sections: {
      news: "お知らせ",
      salesShortcut: "販売のご案内",
      overview: "Event概要",
      schedule: "開催日時",
      venue: "会場・アクセス",
      notices: "注意事項",
      faq: "FAQ",
    },
    news: { viewAll: "すべて見る" },
    shortcut: {
      entry: "Entry Ticketを見る",
      karaoke: "Karaokeを見る",
      goods: "Goodsを見る",
    },
    period: {
      range: (start: string, end: string): string => `${start} 〜 ${end}`,
      from: (start: string): string => `${start} から`,
      until: (end: string): string => `${end} まで`,
    },
  },
  announcements: {
    heading: "お知らせ",
    subject: "お知らせ",
    backToList: "お知らせ一覧へ戻る",
    backHome: "Event Homeへ戻る",
  },
  order: {
    state: {
      PREPARED: "支払い手続き未開始 / 準備済み",
      AWAITING_PAYMENT: "支払い結果を確認中",
      CONFIRMED: "購入確定",
      PAYMENT_FAILED: "支払い不成立",
      CANCELED: "購入手続き取消済み",
      EXPIRED: "購入手続き失効",
      REVIEW_REQUIRED: "購入状態を確認中",
    },
    description: {
      PREPARED: "支払い手続きはまだ始まっていません。同じ購入手続きで支払い開始を再試行できます。",
      AWAITING_PAYMENT: "支払い結果を確認しています。結果が確定するまでお待ちください。",
      CONFIRMED: "購入が確定しました。Ticket / Reservation / Goodsを利用できます。",
      PAYMENT_FAILED: "支払いが成立しませんでした。必要な場合は新しく購入してください。",
      CANCELED: "この購入手続きは取り消されました。",
      EXPIRED: "この購入手続きは有効期限が切れました。",
      REVIEW_REQUIRED: "購入状態を確認しています。確認が終わるまでお待ちください。",
    },
    action: {
      retry_checkout: "支払い開始を再試行",
      recheck_status: "状態を再確認",
      view_purchase: "購入内容を見る",
      view_entitlements: "Ticket / Reservation / Goodsを見る",
      purchase_again: "もう一度購入する",
    },
  },
  purpose: {
    ENTRY_TICKET_PURCHASE: "Entry Ticketの購入",
    KARAOKE_PURCHASE: "Karaoke Ticketの購入",
    GOODS_PURCHASE: "Goodsの購入",
    ENTRY_GOODS_PURCHASE: "Entry TicketとGoodsの購入",
  },
  qr: {
    ENTRY: "Entry Ticket / 入場受付用",
    KARAOKE: "Karaoke Ticket / Karaoke受付用",
  },
  entryTicket: {
    label: {
      VALID: "利用可能",
      USED: "使用済み",
      CANCELED: "取消済み",
      EXPIRED: "失効済み",
    },
    description: {
      VALID: "入場受付でQRを提示できます。",
      USED: "このEntry Ticketはすでに使用されています。",
      CANCELED: "このEntry Ticketは取り消されています。",
      EXPIRED: "このEntry Ticketは有効期限が切れています。",
    },
    disabledReason: {
      USED: "使用済みのためQRは表示できません。",
      CANCELED: "取消済みのためQRは表示できません。",
      EXPIRED: "失効済みのためQRは表示できません。",
    },
  },
  karaoke: {
    slot: {
      label: {
        AVAILABLE: "選択可能",
        HELD: "他の方が確保中",
        SOLD: "販売済み",
        SALES_STOPPED: "販売停止",
      },
      description: {
        AVAILABLE: "この枠を選択できます。",
        HELD: "現在確保中のため選択できません。",
        SOLD: "この枠は販売済みです。",
        SALES_STOPPED: "この枠は販売を停止しています。",
      },
    },
    hold: {
      label: {
        ACTIVE: "購入試行中の確保",
        COMMITTED: "確定購入に使用済み",
        RELEASED: "確保は終了",
        EXPIRED: "確保は期限切れ",
      },
      description: {
        ACTIVE: "購入手続き中の仮確保です。Reservationの確定ではありません。",
        COMMITTED: "この確保は確定購入に使用されました。",
        RELEASED: "この確保は終了しており、再利用できません。",
        EXPIRED: "確保の期限が切れました。新しく枠を確保してください。",
      },
    },
    reservation: {
      CONFIRMED: "予約確定",
      CANCELED: "予約取消済み",
    },
    ticket: {
      VALID: "受付利用可能",
      USED: "使用済み",
      CANCELED: "取消済み",
      EXPIRED: "失効済み",
    },
    primary: {
      VALID: "受付利用可能",
      USED: "使用済み",
      CANCELED: "取消済み",
      EXPIRED: "失効済み",
    },
    disabledReason: {
      reservationCanceled: "予約が取り消されたためQRは表示できません。",
      USED: "使用済みのためQRは表示できません。",
      CANCELED: "取消済みのためQRは表示できません。",
      EXPIRED: "失効済みのためQRは表示できません。",
    },
    guide: {
      heading: "Karaoke 販売案内",
      subject: "Karaoke販売案内",
      intro: "Karaokeは、開催期間中の販売対象日から枠を選んで購入する、時間枠単位の販売です。",
      usageUnit: "1回の購入で、1つの枠を1組で利用できます。",
      duration:
        "利用時間は1枠あたり15分です。枠と枠のあいだには整備時間5分を設けて運用しますが、表示される利用時刻は利用時間を基準にしています。",
      purchaseLimit:
        "購入できる枠数には上限があります。上限を超える場合は、購入手続きの前にお知らせします。",
      priceLabel: "価格",
      periodLabel: "販売期間",
      statusLabel: "販売状態",
      datesHeading: "販売対象日",
      datesEmpty: "現在、販売対象日はありません",
      dateLink: (dateText: string): string => `${dateText}の空き状況を見る`,
    },
    saleStatus: {
      description: {
        ON_SALE: "現在販売中です。販売対象日を選んで、空き状況を確認してください。",
        BEFORE_SALES: "販売開始前のため、現在は購入できません。販売期間をご確認ください。",
        SALES_ENDED: "販売は終了しました。新しく購入することはできません。",
        SUSPENDED: "現在、販売を一時停止しています。既存の予約は取り消されません。",
      },
    },
    day: {
      heading: "Karaoke 空き状況",
      subject: "空き状況",
      previous: "前の販売日",
      next: "次の販売日",
      reload: "空き状況を再読み込み",
      empty: "この日に販売対象の枠はありません",
      unavailable: "空き状況を取得できません",
      bucketCount: (available: number, total: number): string =>
        `空き ${available} / 全 ${total} 枠`,
      slotLink: (timeText: string): string => `${timeText}の枠を選ぶ`,
      backToGuide: "販売案内へ戻る",
    },
  },
  goods: {
    item: {
      PENDING_PAYMENT: "支払未確定・受け取り不可",
      FULFILLABLE: "支払確定済み",
      CANCELED: "取消済み・受け取り不可",
    },
    handoff: {
      PENDING: "未受け渡し",
      COMPLETED: "受け渡し済み",
      VOID: "受け渡し対象外",
    },
    awaiting: "会場受け取り待ち",
    description: {
      canceled: "このGoodsは取り消されており、受け取れません。",
      pendingPayment: "支払いが確定するまで受け取れません。",
      completed: "このGoodsはすでに受け渡し済みです。",
      awaiting: "会場で受け取ってください。",
    },
    list: { heading: "Goods", subject: "Goods一覧" },
    detail: {
      pageTitle: "Goods詳細",
      heading: "Goods詳細",
      subject: "Goods情報",
      pickupNotice: "このGoodsは会場でのお受け取り専用です。",
      backToList: "Goods一覧へ戻る",
    },
  },
  cart: {
    pageTitle: "カート",
    heading: "カート",
    subject: "カートの現在状態",
    empty: "カートは空です",
    backToEntry: "Entry Ticketを見る",
    backToGoods: "Goodsを見る",
    unknownItemName: "状態を確認できない商品",
    kind: { ENTRY_TICKET: "Entry Ticket", GOODS: "Goods" },
    unitPriceLabel: "単価",
    subtotalLabel: "小計",
    remove: "削除",
    summary: {
      heading: "合計",
      totalLabel: "表示用合計",
      recalcNote: "購入時の金額はサーバーで再計算されます",
      onePayment: "Entry TicketとGoodsは1回の支払いにまとめられます",
      totalUnknown: "一部の商品の状態を確認できないため、合計を表示できません",
    },
    karaoke: {
      heading: "Karaokeについて",
      body: "Karaokeはカートに入れられません。Entry TicketやGoodsとは別の購入、別の支払いになります。",
      link: "Karaoke販売案内を見る",
    },
    proceed: {
      label: "購入手続きへ進む",
      blocked:
        "購入できない商品があるため、進めません。該当する商品を削除するか、数量を変更してください。",
      unknown: "現在の状態を確認できないため、購入手続きへ進めません。",
    },
    corrupted: {
      title: "カートを読み込めません",
      description:
        "保存されているカートの内容を確認できません。空のカートとして扱うことはしません。リセットすると、空のカートから始められます。",
      reset: "カートをリセットする",
      goToCart: "カートを確認する",
    },
  },
  quantity: {
    label: "数量",
    invalid: "数量は1以上の整数で入力してください",
    exceedsMax: (max: number): string => `数量は${max}以下で入力してください`,
    guidance: (max: number): string => `1から${max}までの数量を選べます`,
  },
  sales: {
    add: "Cartに追加",
    addSucceeded: "Cartに追加しました。購入はまだ確定していません",
    addFailed: "ブラウザの保存領域に書き込めなかったため、Cartを更新できませんでした",
    viewCart: "Cartを見る",
    displayTotalLabel: "表示用合計",
    displayTotalNote: "購入時の金額はサーバーで再計算されます",
    priceLabel: "価格",
    periodLabel: "販売期間",
    statusLabel: "販売状態",
  },
  entry: {
    pageTitle: "Entry Ticket",
    heading: "Entry Ticket",
    subject: "Entry Ticket情報",
    perAccountLimit: (limit: number): string => `1アカウントあたりの購入上限は${limit}枚です`,
  },
  notification: {
    PENDING: {
      label: "確認Emailを送信中",
      message: "確認Emailを準備しています。購入内容には影響しません。",
    },
    SENT: {
      label: "確認Emailを送信済み",
      message: "確認Emailを送信しました。",
    },
    FAILED_RETRYABLE: {
      label: "確認Emailの送信に失敗または遅延",
      message:
        "購入は確定済みです。確認Emailの送信に失敗または遅延しています。購入内容はこの画面とMypageで確認できます",
    },
  },
  availability: {
    label: {
      ON_SALE: "販売中",
      BEFORE_SALES: "販売開始前",
      SALES_ENDED: "販売終了",
      SUSPENDED: "販売停止",
      SOLD_OUT: "売り切れ",
      INSUFFICIENT_QUANTITY: "数量不足",
      PURCHASE_LIMIT_EXCEEDED: "購入上限により購入不可",
      NOT_PUBLIC: "現在取り扱っていません",
      UNAVAILABLE: "状態を確認できません",
      ALLOCATION_CONFLICT: "在庫の確保に失敗",
    },
    description: {
      ON_SALE: "購入できます。",
      BEFORE_SALES: "販売開始前のため購入できません。",
      SALES_ENDED: "販売期間は終了しました。",
      INSUFFICIENT_QUANTITY: "在庫が不足しています。数量を変更してください。",
      SUSPENDED: "現在、販売を停止しています。",
      SOLD_OUT: "売り切れのため購入できません。",
      PURCHASE_LIMIT_EXCEEDED: "購入上限を超えるため購入できません。",
      NOT_PUBLIC: "この商品は現在取り扱っていません。",
      UNAVAILABLE: "現在の状態を取得できません。時間をおいて再度お試しください。",
      ALLOCATION_CONFLICT: "他の購入と重なり確保できませんでした。内容を確認してください。",
    },
    beforeSales: (startsAtText: string): string => `${startsAtText}から販売を開始します。`,
    insufficientQuantity: (max: string): string =>
      `在庫が不足しています。数量を${max}以下に変更してください。`,
  },
  layout: {
    skipLink: "メインコンテンツへ移動",
    nav: {
      primaryLabel: "メインナビゲーション",
      footerLabel: "フッターナビゲーション",
      items: {
        event: "Event",
        entry: "Entry Ticket",
        karaoke: "Karaoke",
        goods: "Goods",
        cart: "カート",
      },
    },
    cta: { buyTickets: "チケットを購入する" },
    cart: { label: "カート", labelWithCount: (count: number): string => `カート（${count}点）` },
    account: {
      login: "ログイン",
      register: "アカウント登録",
      mypage: "マイページ",
      menuButton: "アカウントメニュー",
      menuLabel: "アカウント",
      profile: "プロフィール",
      orders: "注文",
      entryTickets: "Entry Ticket",
      karaoke: "Karaoke",
      goods: "Goods",
      logout: "ログアウト",
    },
    drawer: { open: "メニューを開く", close: "メニューを閉じる", title: "メニュー" },
    sponsors: { regionLabel: "協賛", externalSuffix: "（外部サイト）" },
    mockBadge: "UIモック表示中",
  },
  auth: {
    gate: {
      subject: "ログイン状態",
      redirecting: "ログイン画面へ移動しています",
    },
    form: {
      errorSummaryTitle: "入力内容を確認してください",
      submitting: "処理中です",
    },
    field: {
      email: {
        label: "メールアドレス",
        required: "メールアドレスを入力してください",
        invalidFormat: "メールアドレスの形式が正しくありません",
      },
      password: {
        label: "パスワード",
        hint: "12文字以上128文字以下で入力してください",
        required: "パスワードを入力してください",
        tooShort: "パスワードは12文字以上で入力してください",
        tooLong: "パスワードは128文字以下で入力してください",
      },
      passwordConfirm: {
        label: "パスワード（確認）",
        mismatch: "確認用のパスワードが一致しません",
      },
      newPassword: { label: "新しいパスワード" },
      newPasswordConfirm: { label: "新しいパスワード（確認）" },
    },
    continuation: {
      notice: "この操作にはログインが必要です",
      returnAfter: "認証後に、元の操作へ戻ります",
      revalidate: "ログイン後に、販売状況や在庫などの現在の状態を確認し直します",
      purpose: {
        cart: "カートの購入手続き",
        karaokeSlot: "Karaoke Ticketの購入手続き",
        purchaseOrder: "購入状況の確認",
        mypage: "マイページの利用",
      },
    },
    register: {
      pageTitle: "アカウント登録",
      heading: "アカウント登録",
      submit: "アカウントを登録する",
      toLogin: "ログインへ",
      rejected: "アカウントを登録できませんでした。入力内容を確認してください",
      unavailable: "登録を完了できません。時間をおいて、もう一度お試しください",
    },
    verify: {
      pageTitle: "メールアドレスの確認",
      heading: "メールアドレスの確認",
      required: "確認メールのリンクを開いて、メールアドレスを確認してください",
      verifying: "メールアドレスを確認しています",
      verified: "メールアドレスを確認しました",
      invalid: "メールアドレスを確認できませんでした。リンクが無効か、期限が切れています",
      unavailable: "確認結果を取得できません。時間をおいて、もう一度お試しください",
      retry: "もう一度確認する",
      toLogin: "ログインへ進む",
      continue: "続きへ進む",
    },
    login: {
      pageTitle: "ログイン",
      heading: "ログイン",
      submit: "ログイン",
      credentialFailure:
        "メールアドレスまたはパスワードが正しくありません。ログインできませんでした",
      unavailable: "ログインを完了できません。時間をおいて、もう一度お試しください",
      toPasswordReset: "パスワードをお忘れの方",
      toRegister: "アカウント登録へ",
      cancel: "ログインせずに戻る",
      passwordUpdated: "パスワードを更新しました。新しいパスワードでログインしてください",
    },
    reset: {
      pageTitle: "パスワードの再設定",
      heading: "パスワードの再設定",
      submit: "再設定の案内を送る",
      accepted:
        "入力されたメールアドレスが登録されている場合、パスワード再設定の案内を送信しました",
      unavailable: "再設定を要求できませんでした。時間をおいて、もう一度お試しください",
      backToLogin: "ログインへ戻る",
    },
    resetComplete: {
      pageTitle: "新しいパスワードの設定",
      heading: "新しいパスワードの設定",
      submit: "パスワードを更新する",
      invalid: "再設定のリンクが無効か、期限が切れています",
      requestAgain: "再設定の案内をもう一度送る",
      unavailable: "パスワードを更新できませんでした。時間をおいて、もう一度お試しください",
    },
  },
  mypage: {
    pageTitle: "マイページ",
    heading: "マイページ",
    protectedMarker: "ログイン中の方だけに表示される内容です",
  },
  notFound: {
    title: "ページを表示できません",
    description: "お探しのページは存在しないか、現在表示できません。",
    homeLink: "Event Homeへ戻る",
  },
  errorPage: {
    title: "問題が発生しました",
    description: "ページを表示できませんでした。時間をおいて、もう一度お試しください。",
    retry: "再試行",
    homeLink: "Event Homeへ戻る",
  },
} as const;
